name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
      contents: read
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'